/**
 * Mock Data for ApartmentAnywhere
 * Sample apartment listings for initial development
 */

import { Apartment } from '@/types/apartment';

export const mockApartments: Apartment[] = [
  {
    id: "apt-1",
    title: "Modern Downtown Loft",
    description: "Stunning loft in the heart of downtown with floor-to-ceiling windows, exposed brick, and modern finishes throughout.",
    monthlyPrice: 2200,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    address: "123 Main St, Apt 4B",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
    amenities: ["Parking", "Washer/Dryer", "Gym", "Rooftop", "Doorman"],
    images: [],
    availableDate: "2025-02-01",
    leaseTerm: "12 months",
    landlordId: "landlord-1",
    createdAt: new Date("2025-01-15")
  },
  {
    id: "apt-2",
    title: "Cozy Studio Apartment",
    description: "Perfect for singles or couples. Great location near restaurants, coffee shops, and public transit.",
    monthlyPrice: 1450,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 650,
    address: "456 Oak Ave",
    city: "Austin",
    state: "TX",
    zipCode: "78702",
    amenities: ["Pet Friendly", "Pool", "Fitness Center"],
    images: [],
    availableDate: "2025-02-15",
    leaseTerm: "6 months",
    landlordId: "landlord-2",
    createdAt: new Date("2025-01-10")
  },
  {
    id: "apt-3",
    title: "Spacious Family Home",
    description: "Great for families, near schools and parks. Large backyard perfect for kids and pets.",
    monthlyPrice: 3500,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2400,
    address: "789 Maple Dr",
    city: "Dallas",
    state: "TX",
    zipCode: "75201",
    amenities: ["Parking", "Backyard", "Pet Friendly", "Fireplace", "Central AC"],
    images: [],
    availableDate: "2025-03-01",
    leaseTerm: "12 months",
    landlordId: "landlord-3",
    createdAt: new Date("2025-01-20")
  },
  {
    id: "apt-4",
    title: "Luxury High-Rise Apartment",
    description: "Premium living with amazing city views. Full-service building with concierge and valet parking.",
    monthlyPrice: 4200,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1500,
    address: "100 Skyline Blvd, Penthouse 1",
    city: "Houston",
    state: "TX",
    zipCode: "77001",
    amenities: ["Concierge", "Pool", "Gym", "Parking", "Doorman", "Valet"],
    images: [],
    availableDate: "2025-02-01",
    leaseTerm: "12 months",
    landlordId: "landlord-4",
    createdAt: new Date("2025-01-08")
  },
  {
    id: "apt-5",
    title: "Charming Bungalow",
    description: "Cozy bungalow with character and charm. Original hardwood floors, updated kitchen, covered porch.",
    monthlyPrice: 1800,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 900,
    address: "222 Pine St",
    city: "San Antonio",
    state: "TX",
    zipCode: "78201",
    amenities: ["Backyard", "Parking", "Washer/Dryer", "Porch"],
    images: [],
    availableDate: "2025-02-15",
    leaseTerm: "6 months",
    landlordId: "landlord-5",
    createdAt: new Date("2025-01-12")
  },
  {
    id: "apt-6",
    title: "Urban Studio",
    description: "Modern studio in walkable neighborhood near shops, restaurants, and entertainment.",
    monthlyPrice: 1650,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 550,
    address: "555 Urban Way",
    city: "Austin",
    state: "TX",
    zipCode: "78703",
    amenities: ["Parking", "Bike Storage", "Pet Friendly", "Community Space"],
    images: [],
    availableDate: "2025-03-01",
    leaseTerm: "Flexible",
    landlordId: "landlord-1",
    createdAt: new Date("2025-01-18")
  },
  {
    id: "apt-7",
    title: "Executive Penthouse",
    description: "Stunning penthouse with panoramic views. Top-of-the-line finishes and smart home technology.",
    monthlyPrice: 7500,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 2800,
    address: "1 Luxury Lane",
    city: "Dallas",
    state: "TX",
    zipCode: "75202",
    amenities: ["Concierge", "Pool", "Gym", "Parking", "Doorman", "Smart Home", "Terrace"],
    images: [],
    availableDate: "2025-04-01",
    leaseTerm: "12 months",
    landlordId: "landlord-4",
    createdAt: new Date("2025-01-05")
  },
  {
    id: "apt-8",
    title: "Cozy One-Bedroom",
    description: "Recently renovated one-bedroom in quiet residential neighborhood.",
    monthlyPrice: 1350,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 720,
    address: "888 Quiet Rd",
    city: "Fort Worth",
    state: "TX",
    zipCode: "76101",
    amenities: ["Parking", "Washer/Dryer", "Pet Friendly"],
    images: [],
    availableDate: "2025-02-01",
    leaseTerm: "6 months",
    landlordId: "landlord-2",
    createdAt: new Date("2025-01-22")
  },
  {
    id: "apt-9",
    title: "Artist's Loft",
    description: "Creative live-work space with high ceilings, large windows, and industrial charm.",
    monthlyPrice: 1900,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 1100,
    address: "42 Art District",
    city: "Houston",
    state: "TX",
    zipCode: "77002",
    amenities: ["High Ceilings", "Natural Light", "Flexible Space", "Parking"],
    images: [],
    availableDate: "2025-02-15",
    leaseTerm: "Flexible",
    landlordId: "landlord-3",
    createdAt: new Date("2025-01-14")
  },
  {
    id: "apt-10",
    title: "Suburban Family Townhouse",
    description: "Three-story townhouse in family-friendly community with pool and parks.",
    monthlyPrice: 2800,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1800,
    address: "123 Family Dr",
    city: "Plano",
    state: "TX",
    zipCode: "75023",
    amenities: ["Parking", "Pool", "Community Park", "Pet Friendly", "Washer/Dryer"],
    images: [],
    availableDate: "2025-03-15",
    leaseTerm: "12 months",
    landlordId: "landlord-5",
    createdAt: new Date("2025-01-25")
  },
  {
    id: "apt-11",
    title: "Micro Studio",
    description: "Efficient micro studio perfect for students or young professionals. Affordable and well-located.",
    monthlyPrice: 1100,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 400,
    address: "99 Campus Way",
    city: "Austin",
    state: "TX",
    zipCode: "78705",
    amenities: ["Furnished", "Utilities Included", "Bike Storage"],
    images: [],
    availableDate: "2025-02-01",
    leaseTerm: "9 months",
    landlordId: "landlord-1",
    createdAt: new Date("2025-01-28")
  },
  {
    id: "apt-12",
    title: "Garden Apartment",
    description: "Ground-floor apartment with private patio garden. Quiet complex with great neighbors.",
    monthlyPrice: 1550,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 850,
    address: "77 Garden Ln",
    city: "San Antonio",
    state: "TX",
    zipCode: "78202",
    amenities: ["Private Patio", "Garden", "Parking", "Pet Friendly"],
    images: [],
    availableDate: "2025-04-01",
    leaseTerm: "12 months",
    landlordId: "landlord-2",
    createdAt: new Date("2025-01-30")
  }
];

export const availableAmenities = [
  { name: "Air Conditioning", category: "essential" },
  { name: "Parking", category: "essential" },
  { name: "Washer/Dryer", category: "essential" },
  { name: "Dishwasher", category: "essential" },
  { name: "Pool", category: "lifestyle" },
  { name: "Gym", category: "lifestyle" },
  { name: "Doorman", category: "luxury" },
  { name: "Concierge", category: "luxury" },
  { name: "Rooftop", category: "lifestyle" },
  { name: "Pet Friendly", category: "lifestyle" },
  { name: "Backyard", category: "lifestyle" },
  { name: "Fireplace", category: "luxury" },
  { name: "Balcony", category: "lifestyle" },
  { name: "Storage", category: "essential" },
  { name: "Furnished", category: "luxury" },
  { name: "Utilities Included", category: "utilities" }
];

export const texasCities = [
  "Austin", "Dallas", "Houston", "San Antonio", "Fort Worth",
  "Plano", "Irving", "Arlington", "Garland", "Lubbock"
];

export const leaseTerms = [
  "3 months",
  "6 months",
  "9 months",
  "12 months",
  "Flexible",
  "Month-to-month"
];
